services:
  ble_server:
    platform: linux/arm64
    stdin_open: true
    tty: true
    build:
        context: ./ble_server
        dockerfile: Dockerfile.ble_server
    image: ble_server:latest
    network_mode: host
    volumes:
      - ./ble_server:/app
  custom-rpi-image:
    privileged: true
    stdin_open: true
    tty: true
    build:
        context: ./custom-rpi-image
        dockerfile: Dockerfile.custom-rpi-image
    image: macmind_rpi_ble_server:latest
    volumes:
      - ./custom-rpi-image:/home/imagegen/custom-rpi-image