[package]
name = "ble_server"
version = "0.1.0"
edition = "2021"

[dependencies]
bluer = { version = "0.17", features = ["full"] }
tokio = { version = "1", features = ["rt", "rt-multi-thread", "macros", "time"] }
uuid = { version = "1.1", features = ["v4"] }
futures = "0.3"